### ISSUE TITLE
SRI support

### ISSUE THREAD

**Issue by ArekZw** [style-tools/async#2]
Is it possible to check the integrity of the file subresource (SRI)? I download resources from CDN and it will be increase security.

**Comment by optimalisatie** [comment]
Hi @ArekZw,

Thank you for the suggestion!

You can define attributes to include on a `<link>` or `<script>` element.

```javascript
$async({
   "href": "https://cdn.com/style.css",
   "attributes": {
      "integrity": "sha384-oqVuAfXRKap7fdgcCY5uykM6+R9GqQ8K/uxy9rx7HNQlGYl1kPzQho1wx4JwY8wC",
      "crossorigin": "anonymous"
   }
});
```

When loading multiple stylesheets, you can define attributes in global options to apply to all stylesheets.

```javascript
$async([{
   "href": "https://cdn.com/style.css",
   "attributes": {
      "integrity": "sha384-oqVuAfXRKap7fdgcCY5uykM6+R9GqQ8K/uxy9rx7HNQlGYl1kPzQho1wx4JwY8wC"
   }
}, {
   "href": "https://cdn.com/style-2.css",
   "attributes": {
      "integrity": "sha384-oqVuAfXRKap7fdgcCY5uykM6+R9GqQ8K/uxy9rx7HNQlGYl1kPzQho1wx4JwY8wC"
   }
}], {
   "attributes": {
      "crossorigin": "anonymous"
   }
});
```

![image](https://user-images.githubusercontent.com/8843669/62923126-57b54480-bdad-11e9-90ae-7916ed1ea8e6.png)

![image](https://user-images.githubusercontent.com/8843669/62923203-83382f00-bdad-11e9-9442-0ccdb0cf8795.png)

The SRI hash should be calculated on the server so you would need to include it manually.

> You use the Subresource Integrity feature by specifying a base64-encoded cryptographic hash of a resource (file) you’re telling the browser to fetch, in the value of the integrity attribute of any <script> or <link> element.

https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

Once setup, you should enforce valid SRI hashes via a HTTP header:

```http
Content-Security-Policy: require-sri-for style;
```

**Comment by ArekZw** [comment]
Wow, nice, thank you! That's exactly what I was looking for.
