### ISSUE TITLE
Double resource load

### ISSUE THREAD

**Issue by ArekZw** [style-tools/async#3]
Sometimes resources are double loaded

Code:
<script async data-c='[
    [ {
        "href": "/test2.css"
    }]
]' src="http://127.0.0.1/loader.js"></script> 

Screenshot:
![Zrzut ekranu z 2020-12-02 03-13-31](https://user-images.githubusercontent.com/11788346/100819378-56010b80-344c-11eb-9c1d-86ee55571fb8.png)

**Comment by optimalisatie** [comment]
Hi @ArekZw,

Our apologies for the late reply.

Thank you for the bug report! The script has been updated a lot since your report and the bug has been fixed since 2020.

If you are still using `$async`, please let us know if the issue is resolved with version `2.0.4`.
